# Base image with Python and TensorFlow
FROM python:3.9-slim

# Install dependencies
RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt

# Create working directory
WORKDIR /app

# Copy app files
COPY app.py my_model.h5 tokenizer.pkl label_encoder.pkl job_data.json /app/

# Expose port
EXPOSE 5000

# Run the application
CMD ["python", "app.py"]
